#cloud-config
packages:
  - git
  - default-jre
  - make
  - gcc
  - libc6-dev
  - libc++-dev
  - clang
  - sudo
users:
  - name: pk910
    primary-group: users
    shell: /bin/bash
    uid: "1000"
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaGa3CFThBknOqAWqn8G4qHcl/U1Lm9CUjZ+zG+CxnBDT6K6CVgHkjEHru7gkrP7LrDKQI7JPPPSO/+ozUWcCoBomjzZ4w2inelUverCRHe2iZBSP9RNqVRc4p2F3NIiOblzYUiXYdXu1I0zFNe4jvkjTtlZ6gb8PiDqUmMs4hRWfIG88ahhwHnBeqEECK0TNra4h4n6wq0rvkGj21xSH0CXw4X6O2a5tdARbAsrMA1pQISX4AKniHcMCAo+gqobXHeN2sP2JMq8SrszjkzH/Xj/vMtBe/iD+eCexPVXRfkMrxtZxseazkJDTB6E6DVoNOZPfqs4RyjE8MahWh3UI/ pk910_root
  - name: etherum
    home: /home/etherum
    shell: /bin/bash
    uid: "1001"
write_files:
  - path: /etc/ssh/sshd_config.d/pknet-ssh.conf
    content: |
      Port 16110
  - path: /etc/sudoers.d/pk910
    content: |
      pk910    ALL=(ALL) NOPASSWD: ALL
  - path: /etc/sudoers.d/etherum
    content: |
      # Cmnd alias specification
      Cmnd_Alias ETH_CMDS = /bin/systemctl stop geth, /bin/systemctl start geth, /bin/systemctl stop beacon-chain, /bin/systemctl start beacon-chain, /bin/systemctl stop validator, /bin/systemctl start validator, /bin/systemctl stop boot-node, /bin/systemctl start boot-node

      # User privilege specification
      etherum    ALL=(ALL) NOPASSWD: ETH_CMDS
  - path: /etc/systemd/system/geth.service
    content: |
      [Unit]
      Description     = geth eth1 service
      Wants           = network-online.target
      After           = network-online.target

      [Service]
      User            = etherum
      WorkingDirectory= /home/etherum/geth
      EnvironmentFile = /home/etherum/testnet/nodevars_env.txt
      ExecStart       = /home/etherum/geth/bin/geth --datadir /home/etherum/data-geth --port 30303 --http --http.addr 0.0.0.0 --http.port 8545 --http.api eth,net,personal,web3 --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.api eth,net,personal,web3 --authrpc.jwtsecret=/home/etherum/jwtsecret --syncmode=full --bootnodes "${BOOTNODE_ENODE_LIST}" --networkid ${CHAIN_ID}
      Restart         = on-failure

      [Install]
      WantedBy= multi-user.target
  - path: /etc/systemd/system/beacon-chain.service
    content: |
      [Unit]
      Description     = eth2 beacon chain service
      Wants           = network-online.target
      After           = network-online.target

      [Service]
      User            = etherum
      WorkingDirectory= /home/etherum/teku
      EnvironmentFile = /home/etherum/testnet/nodevars_env.txt
      ExecStart       = /home/etherum/teku/bin/teku --Xee-version kilnv2 --network=/home/etherum/testnet/config.yaml --initial-state=/home/etherum/testnet/genesis.ssz --data-path=/home/etherum/data-teku --data-storage-mode=PRUNE --p2p-enabled=true --eth1-endpoints=http://localhost:8545 --rest-api-enabled=true --rest-api-docs-enabled=true --rest-api-interface=0.0.0.0 --rest-api-host-allowlist=* --data-storage-non-canonical-blocks-enabled=true --ee-endpoint=http://localhost:8551 --ee-jwt-secret-file=/home/etherum/jwtsecret --validators-proposer-default-fee-recipient=0x14627ea0e2B27b817DbfF94c3dA383bB73F8C30b --p2p-discovery-bootnodes="${BOOTNODE_ENR_LIST}"
      Restart         = on-failure

      [Install]
      WantedBy= multi-user.target
  - path: /etc/systemd/system/validator.service
    content: |
      [Unit]
      Description     = eth2 validator service
      Wants           = network-online.target beacon-chain.service
      After           = network-online.target

      [Service]
      User            = etherum
      WorkingDirectory= /home/etherum/teku
      ExecStart       = /home/etherum/teku/bin/teku validator-client --network=/home/etherum/testnet/config.yaml --beacon-node-api-endpoint=http://localhost:5051 --validator-keys=/home/etherum/data-keys/teku-keys:/home/etherum/data-keys/teku-secrets --validators-graffiti="pk910 (3)" --validators-proposer-default-fee-recipient=0x14627ea0e2B27b817DbfF94c3dA383bB73F8C30b
      Restart         = on-failure

      [Install]
      WantedBy= multi-user.target
  - path: /home/etherum/setup.sh
    content: |
      #!/bin/bash
      cd ~
      if ! [ -f ./setup-clients.sh ]; then
        wget https://raw.githubusercontent.com/pk910/test-testnet-scripts/master/resources/setup-clients.sh
      fi
      source ./setup-clients.sh
      homepath=$(pwd)
      export PATH=$homepath/golang/bin:$homepath/go/bin:$PATH
      mkdir -p src
      cd src

      setup_golang
      setup_eth2valtools
      setup_geth
      setup_teku
      setup_jwtsecret

  - path: /home/etherum/retention.sh
    content: |
      #!/bin/bash

      genesis_repository="pk910/test-testnet-repo"
      testnet_dir=/home/etherum/testnet
      el_datadir=/home/etherum/data-geth
      cl_datadir=/home/etherum/data-teku
      cl_port=5051


      start_clients() {
        # start EL / CL clients
        echo "start clients"
        sudo /bin/systemctl start geth
        sudo /bin/systemctl start beacon-chain
        sudo /bin/systemctl start validator
      }

      stop_clients() {
        # stop EL / CL clients
        echo "stop clients"
        sudo /bin/systemctl stop geth
        sudo /bin/systemctl stop beacon-chain
        sudo /bin/systemctl stop validator
      }

      clear_datadirs() {
        if [ -d $el_datadir/geth ]; then
          geth_nodekey=$(cat $el_datadir/geth/nodekey)
          rm -rf $el_datadir/geth
          mkdir $el_datadir/geth
          echo $geth_nodekey > $el_datadir/geth/nodekey
        fi

        rm -rf $cl_datadir/*
        rm -rf /home/etherum/.local/share/teku
      }

      setup_genesis() {
        # init el genesis
        ~/geth/bin/geth init --datadir $el_datadir $testnet_dir/genesis.json
      }

      source ~/retention-lib.sh
      retention_main

  - path: /home/etherum/setup-retention.sh
    content: |
      #!/bin/bash
      cd /home/etherum
      chmod +x retention.sh
      wget https://raw.githubusercontent.com/pk910/test-testnet-scripts/master/resources/retention-lib.sh
      ./retention.sh
      (2>/dev/null crontab -l ; echo "*/5 * * * * /home/etherum/retention.sh") | crontab -
  - path: /home/etherum/setup-validators.sh
    content: |
      #!/bin/bash
      cd /home/etherum
      export PATH=/home/etherum/golang/bin:/home/etherum/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

      # validator mnemonic
      mnemonic="*** INSERT VALIDATOR MNEMONIC HERE ***"
      validator_count="100"
      
      eth2-val-tools keystores --insecure --prysm-pass password --out-loc /home/etherum/data-keys --source-mnemonic "$mnemonic" --source-max 100
runcmd:
  - [ chown, -R, "etherum:etherum", /home/etherum ]
  - [ chmod, +x, /home/etherum/setup.sh ]
  - [ sudo, -u, etherum, /home/etherum/setup.sh ]
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, geth.service ]
  - [ systemctl, enable, beacon-chain.service ]
  - [ systemctl, enable, validator.service ]
  - [ chmod, +x, /home/etherum/setup-validators.sh ]
  - [ sudo, -u, etherum, /home/etherum/setup-validators.sh ]
  - [ chmod, +x, /home/etherum/setup-retention.sh ]
  - [ sudo, -u, etherum, /home/etherum/setup-retention.sh ]


