#cloud-config
packages:
  - git
  - make
  - cmake
  - g++
  - pkg-config
  - llvm-dev
  - libclang-dev
  - clang
  - protobuf-compiler
  - gcc
  - libc6-dev
  - sudo
  - postgresql
  - postgresql-contrib
  - ca-certificates
  - gnupg
  - lsb-release
users:
  - name: pk910
    primary-group: users
    shell: /bin/bash
    uid: "1000"
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaGa3CFThBknOqAWqn8G4qHcl/U1Lm9CUjZ+zG+CxnBDT6K6CVgHkjEHru7gkrP7LrDKQI7JPPPSO/+ozUWcCoBomjzZ4w2inelUverCRHe2iZBSP9RNqVRc4p2F3NIiOblzYUiXYdXu1I0zFNe4jvkjTtlZ6gb8PiDqUmMs4hRWfIG88ahhwHnBeqEECK0TNra4h4n6wq0rvkGj21xSH0CXw4X6O2a5tdARbAsrMA1pQISX4AKniHcMCAo+gqobXHeN2sP2JMq8SrszjkzH/Xj/vMtBe/iD+eCexPVXRfkMrxtZxseazkJDTB6E6DVoNOZPfqs4RyjE8MahWh3UI/ pk910_root
  - name: etherum
    home: /home/etherum
    shell: /bin/bash
    uid: "1001"
  - name: beaconchain
    home: /home/beaconchain
    shell: /bin/bash
    uid: "1003"
write_files:
  - path: /etc/ssh/sshd_config.d/pknet-ssh.conf
    content: |
      Port 16110
  - path: /etc/sudoers.d/pk910
    content: |
      pk910    ALL=(ALL) NOPASSWD: ALL
  - path: /etc/sudoers.d/etherum
    content: |
      # Cmnd alias specification
      Cmnd_Alias ETH_CMDS = /bin/systemctl stop geth, /bin/systemctl start geth, /bin/systemctl stop beacon-chain, /bin/systemctl start beacon-chain, /bin/systemctl stop validator, /bin/systemctl start validator, /bin/systemctl stop boot-node, /bin/systemctl start boot-node, /home/beaconchain/start.sh, /home/beaconchain/stop.sh, /home/beaconchain/reset.sh, /root/reset-beaconchain-db.sh

      # User privilege specification
      etherum    ALL=(ALL) NOPASSWD: ETH_CMDS
  - path: /etc/systemd/system/geth.service
    content: |
      [Unit]
      Description     = geth eth1 service
      Wants           = network-online.target
      After           = network-online.target

      [Service]
      User            = etherum
      WorkingDirectory= /home/etherum/geth
      EnvironmentFile = /home/etherum/testnet/nodevars_env.txt
      ExecStart       = /home/etherum/geth/bin/geth --datadir /home/etherum/data-geth --port 30303 --http --http.addr 0.0.0.0 --http.port 8545 --http.api eth,net,personal,web3,txpool,debug --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.api eth,net,personal,web3,txpool,debug --authrpc.jwtsecret=/home/etherum/jwtsecret --syncmode=full --bootnodes "${BOOTNODE_ENODE_LIST}" --networkid ${CHAIN_ID}
      Restart         = on-failure

      [Install]
      WantedBy= multi-user.target
  - path: /etc/systemd/system/beacon-chain.service
    content: |
      [Unit]
      Description     = eth2 beacon chain service
      Wants           = network-online.target
      After           = network-online.target

      [Service]
      User            = etherum
      WorkingDirectory= /home/etherum/lighthouse
      EnvironmentFile = /home/etherum/testnet/nodevars_env.txt
      ExecStart       = /home/etherum/lighthouse/lighthouse bn --testnet-dir /home/etherum/testnet --datadir /home/etherum/data-lh --staking --metrics --port 9010 --http-address 0.0.0.0 --metrics-address 0.0.0.0 --execution-endpoint http://127.0.0.1:8551 --execution-jwt="/home/etherum/jwtsecret" --boot-nodes ${BOOTNODE_ENR_LIST}
      Restart         = on-failure

      [Install]
      WantedBy= multi-user.target
  - path: /etc/systemd/system/validator.service
    content: |
      [Unit]
      Description     = eth2 validator service
      Wants           = network-online.target beacon-chain.service
      After           = network-online.target

      [Service]
      User            = etherum
      WorkingDirectory= /home/etherum/lighthouse
      ExecStart       = /home/etherum/lighthouse/lighthouse vc --testnet-dir /home/etherum/testnet --datadir /home/etherum/data-lh --beacon-nodes "http://localhost:5052" --graffiti "pk910 (2)" --suggested-fee-recipient 0x14627ea0e2B27b817DbfF94c3dA383bB73F8C30b --init-slashing-protection --allow-unsynced
      Restart         = on-failure

      [Install]
      WantedBy= multi-user.target
  - path: /root/reset-beaconchain-db.sh
    content: |
      #!/bin/bash

      sudo -u postgres bash -c "cd ~ && dropdb beaconchain"
      sudo -u postgres bash -c "cd ~ && createdb beaconchain -O beaconchain"
      
  - path: /root/setup.sh
    content: |
      #!/bin/bash
      wget https://raw.githubusercontent.com/ephemery-testnet/ephemery-scripts/master/resources/setup-services.sh
      source ./setup-services.sh
      chmod +x /root/reset-*

      setup_docker
      setup_pgsql
      setup_pgsql_user beaconchain /home/beaconchain/.dbpassword.txt
      usermod -a -G docker beaconchain

  - path: /home/etherum/setup.sh
    content: |
      #!/bin/bash
      cd ~
      if ! [ -f ./setup-clients.sh ]; then
        wget https://raw.githubusercontent.com/ephemery-testnet/ephemery-scripts/master/resources/setup-clients.sh
      fi
      source ./setup-clients.sh
      src_link_path="$(pwd)"
      mkdir -p src
      cd src

      setup_golang
      setup_rust
      setup_geth
      setup_lighthouse

  - path: /home/etherum/retention.sh
    content: |
      #!/bin/bash

      genesis_repository="ephemery-testnet/ephemery-genesis"
      testnet_dir=/home/etherum/testnet
      el_datadir=/home/etherum/data-geth
      cl_datadir=/home/etherum/data-lh
      cl_port=5052


      start_clients() {
        # start EL / CL clients
        echo "start clients"
        sudo /bin/systemctl start geth
        sudo /bin/systemctl start beacon-chain
        sudo /bin/systemctl start validator
        sudo -u beaconchain /home/beaconchain/start.sh
      }

      stop_clients() {
        # stop EL / CL clients
        echo "stop clients"
        sudo /bin/systemctl stop geth
        sudo /bin/systemctl stop beacon-chain
        sudo /bin/systemctl stop validator
        sudo -u beaconchain /home/beaconchain/stop.sh
      }

      clear_datadirs() {
        if [ -d $el_datadir/geth ]; then
          geth_nodekey=$(cat $el_datadir/geth/nodekey)
          rm -rf $el_datadir/geth
          mkdir $el_datadir/geth
          echo $geth_nodekey > $el_datadir/geth/nodekey
        fi

        rm -rf $cl_datadir/beacon
        rm -rf $cl_datadir/validators/slashing_protection.sqlite

        sudo /root/reset-beaconchain-db.sh
      }

      setup_genesis() {
        # init el genesis
        ~/geth/bin/geth init --datadir $el_datadir $testnet_dir/genesis.json

        sudo -u beaconchain /home/beaconchain/reset.sh
      }

      source ~/retention-lib.sh
      retention_main

  - path: /home/etherum/setup-retention.sh
    content: |
      #!/bin/bash
      cd /home/etherum
      chmod +x retention.sh
      wget https://raw.githubusercontent.com/ephemery-testnet/ephemery-scripts/master/resources/retention-lib.sh
      ./retention.sh
      (2>/dev/null crontab -l ; echo "*/5 * * * * /home/etherum/retention.sh") | crontab -
  - path: /home/etherum/setup-validators.sh
    content: |
      #!/bin/bash
      cd /home/etherum
      
      # ADD YOUR VALIDATOR MNEMONIC HERE
      validator_mnemonic=""
      validator_count=100

      if [ ! -z "$validator_mnemonic" ]; then
        echo $validator_mnemonic | lighthouse/lighthouse account validator recover --datadir /home/etherum/data-lh --stdin-inputs --count $validator_count
      fi

  - path: /home/beaconchain/setup.sh
    content: |
      #!/bin/bash
      cd /home/beaconchain
      chmod +x start.sh
      chmod +x stop.sh
      chmod +x reset.sh

      mkdir -p ./data-explorer
      wget -O ./data-explorer/tables.sql https://raw.githubusercontent.com/ephemery-testnet/ephemery-scripts/master/resources/beaconchain-tables.sql
      wget -O ./explorer-config.yaml https://raw.githubusercontent.com/ephemery-testnet/ephemery-scripts/master/resources/beaconchain-config.yaml
      
  - path: /home/beaconchain/start.sh
    content: |
      #!/bin/bash

      docker run -d --restart unless-stopped --name=cl_explorer \
        -p 3333:3333 \
        -v /home/etherum/testnet:/config_testnet \
        -v /home/beaconchain/data-explorer:/config \
        -it 'parithoshj/beacon-explorer:print-chain-id' \
        ./explorer --config /config/config.yaml

  - path: /home/beaconchain/stop.sh
    content: |
      #!/bin/bash

      docker stop cl_explorer
      docker rm cl_explorer

  - path: /home/beaconchain/reset.sh
    content: |
      #!/bin/bash
      cd /home/beaconchain

      # assume a clean database here
      # import tables
      psql -f ./data-explorer/tables.sql

      # generate explorer configuration
      export DB_PASSWORD=$(cat ./.dbpassword.txt | tr -d " \n")
      source /home/etherum/testnet/nodevars_env.txt

      cl_config=/home/etherum/testnet/config.yaml
      genesis_time=$(cat $cl_config | grep "MIN_GENESIS_TIME" | sed 's/^.*: \(.*\)$/\1/')
      genesis_delay=$(cat $cl_config | grep "GENESIS_DELAY" | sed 's/^.*: \(.*\)$/\1/')
      export GENESIS_TIMESTAMP=$(expr $genesis_time + $genesis_delay)
      export MIN_GENESIS_VALIDATORS=$(cat $cl_config | grep "MIN_GENESIS_ACTIVE_VALIDATOR_COUNT" | sed 's/^.*: \(.*\)$/\1/')
      export ITERATION_NUMBER=$ITERATION_NUMBER

      export DEPOSIT_CONTRACT_ADDR=$(cat /home/etherum/testnet/deposit_contract.txt | tr -d " \n")
      export DEPOSIT_CONTRACT_BLOCK=$(cat /home/etherum/testnet/deploy_block.txt | tr -d " \n")

      envsubst < ./explorer-config.yaml > ./data-explorer/config.yaml

runcmd:
  - [ chmod, +x, /root/setup.sh ]
  - [ /root/setup.sh ]
  - [ chown, -R, "etherum:etherum", /home/etherum ]
  - [ chown, -R, "beaconchain:beaconchain", /home/beaconchain ]
  - [ chmod, +x, /home/etherum/setup.sh ]
  - [ sudo, -u, etherum, /home/etherum/setup.sh ]
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, geth.service ]
  - [ systemctl, enable, beacon-chain.service ]
  - [ systemctl, enable, validator.service ]
  - [ chmod, +x, /home/etherum/setup-validators.sh ]
  - [ sudo, -u, etherum, /home/etherum/setup-validators.sh ]
  - [ chmod, +x, /home/beaconchain/setup.sh ]
  - [ sudo, -u, beaconchain, /home/beaconchain/setup.sh ]
  - [ chmod, +x, /home/etherum/setup-retention.sh ]
  - [ sudo, -u, etherum, /home/etherum/setup-retention.sh ]
